apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeonec.fullname" . }}-service
  labels:
    {{- include "kubeonec.labels" . | nindent 4 }}
spec:
  ports:
      {{- range untilStep (int .Values.ports.workProccesStartPort) (int .Values.workProccesEndPort) 1 }}  
        - protocol: TCP
          name: wp-{{ . }}
          port: {{ (int .) }}
      {{- end }}
        - protocol: TCP
          name: clmen
          port: {{ .Values.ports.serveragent }}
        - protocol: TCP
          name: cluster
          port: {{ .Values.ports.clusterManagerPort }}
        - name: ras
          port: {{ .Values.ports.rasPort }}
  clusterIP: None
  selector:
    app: server
