{{- $createPvc := and (empty .Values.storage.persistentVolumeClaimName) (.Values.storage.requestedSize) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kubeonec.fullname" . }}
  labels:
    version: " {{- .Values.image.tag }}"
    {{- include "kubeonec.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "kubeonec.fullname" . }}
  selector:
    matchLabels:
      {{- include "kubeonec.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "kubeonec.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext: {{- omit .Values.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create}}
      serviceAccount: {{ include "kubeonec.serviceAccountName" . }}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: server
        {{- if .Values.image.tag }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- else }}
        image: "{{ .Values.image.repository }}:latest"
        {{- end }}
        imagePullPolicy: Always
        ports:
          - name: rmngr
            containerPort: {{ .Values.ports.clusterManagerPort }}  
            protocol: TCP
          {{- range untilStep (int .Values.ports.workProccesStartPort) (int .Values.ports.workProccesEndPort) 1 }}  
          - name: "rphost-{{ . }}"
            containerPort: {{ . }}
            protocol: TCP
          {{- end }}
          - name: ragent
            containerPort: {{ .Values.ports.serverAgent }}
            protocol: TCP
          - name: ras
            containerPort: {{ .Values.ports.rasPort }}
            protocol: TCP
        volumeMounts:
        - name: {{ .Values.storage.volumeName }}
          mountPath: /home
        {{- if .Values.useHasp }}    
        - name: aksusb
          mountPath: /tmp/.aksusb
        {{- end }}
      volumes:
      {{- if .Values.useHasp }}
      - name: aksusb
        hostPath:
          path: /tmp/.aksusb
      {{- end }}
  {{- with .Values.storage }}
  {{- if not $createPvc }}
      - name: {{ .volumeName }}
      {{- if .persistentVolumeClaimName }}
        persistentVolumeClaim:
          claimName: {{ .persistentVolumeClaimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
  {{- else }}      
  volumeClaimTemplates:
    - metadata:
        name: {{ .volumeName }}
      {{- with .labels }}
        labels:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .annotations }}
        annotations:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      spec:
        {{- with .accessModes }}
        accessModes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .className }}
        storageClassName: {{ .className }}
        {{- end }}
        resources:
          requests:
            storage: {{ .requestedSize }}
  {{- end }}
  {{- end }}
